# Generated by Django 5.1.4 on 2025-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accessory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_for_one_day",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("image", models.ImageField(upload_to="equipment/")),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("brand", models.CharField(max_length=100)),
                (
                    "additional_info",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "person",
                    models.CharField(
                        choices=[
                            ("Men", "Men"),
                            ("Women", "Women"),
                            ("Kids", "Kids"),
                            ("Unisex", "Unisex"),
                        ],
                        default="Unisex",
                        max_length=100,
                    ),
                ),
                ("accessory_type", models.CharField(max_length=50)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_for_one_day",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("image", models.ImageField(upload_to="equipment/")),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("brand", models.CharField(max_length=100)),
                (
                    "additional_info",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "person",
                    models.CharField(
                        choices=[
                            ("Men", "Men"),
                            ("Women", "Women"),
                            ("Kids", "Kids"),
                            ("Unisex", "Unisex"),
                        ],
                        default="Unisex",
                        max_length=100,
                    ),
                ),
                ("bike_type", models.CharField(max_length=100)),
                ("gear_num", models.PositiveIntegerField()),
                ("usage", models.CharField(max_length=100)),
                ("has_bell", models.BooleanField(default=False)),
                ("has_trunk", models.BooleanField(default=False)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, max_digits=4, null=True),
                ),
                ("wheel_size_cm", models.DecimalField(decimal_places=2, max_digits=4)),
                ("brake_type", models.CharField(max_length=50, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
