# Generated by Django 5.1.4 on 2025-01-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="review", name="status",),
        migrations.AddField(
            model_name="review",
            name="does_exists",
            field=models.BooleanField(default=False),
        ),
    ]
