# Generated by Django 5.1.4 on 2025-01-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_order_date"),
        ("review", "0002_remove_review_status_review_does_exists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="order.order",
            ),
        ),
    ]
