# Generated by Django 5.1.4 on 2025-01-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_rev_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order", name="rev_num", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
