# Generated by Django 5.1.4 on 2025-01-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_order_rev_num_alter_order_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="rev_num",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
